# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kvstore_pb2 as kvstore__pb2


class CacheServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/kvstore.CacheService/Put',
                request_serializer=kvstore__pb2.Item.SerializeToString,
                response_deserializer=kvstore__pb2.Item.FromString,
                )
        self.Get = channel.unary_unary(
                '/kvstore.CacheService/Get',
                request_serializer=kvstore__pb2.GetParams.SerializeToString,
                response_deserializer=kvstore__pb2.Item.FromString,
                )
        self.GetAllItems = channel.unary_stream(
                '/kvstore.CacheService/GetAllItems',
                request_serializer=kvstore__pb2.AllItemsParams.SerializeToString,
                response_deserializer=kvstore__pb2.AllItems.FromString,
                )
        self.Delete = channel.unary_unary(
                '/kvstore.CacheService/Delete',
                request_serializer=kvstore__pb2.GetParams.SerializeToString,
                response_deserializer=kvstore__pb2.Success.FromString,
                )


class CacheServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=kvstore__pb2.Item.FromString,
                    response_serializer=kvstore__pb2.Item.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=kvstore__pb2.GetParams.FromString,
                    response_serializer=kvstore__pb2.Item.SerializeToString,
            ),
            'GetAllItems': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllItems,
                    request_deserializer=kvstore__pb2.AllItemsParams.FromString,
                    response_serializer=kvstore__pb2.AllItems.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kvstore__pb2.GetParams.FromString,
                    response_serializer=kvstore__pb2.Success.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvstore.CacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CacheService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.CacheService/Put',
            kvstore__pb2.Item.SerializeToString,
            kvstore__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.CacheService/Get',
            kvstore__pb2.GetParams.SerializeToString,
            kvstore__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/kvstore.CacheService/GetAllItems',
            kvstore__pb2.AllItemsParams.SerializeToString,
            kvstore__pb2.AllItems.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.CacheService/Delete',
            kvstore__pb2.GetParams.SerializeToString,
            kvstore__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
